"""add system_parameters table

Revision ID: 1810197e79a8
Revises: 28fa4a682b3f
Create Date: 2026-04-15 15:46:12.720209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1810197e79a8'
down_revision = '28fa4a682b3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_parameters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_parameters_key'), ['key'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_parameters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_parameters_key'))

    op.drop_table('system_parameters')
    # ### end Alembic commands ###
