"""Allow null fields for manual reports

Revision ID: 5eb09ec685cb
Revises: fe4a9c9b82a4
Create Date: 2026-04-24 12:09:50.216798

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5eb09ec685cb'
down_revision = 'fe4a9c9b82a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_behaviors', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'behaviors', ['behavior_id'], ['id'])

    with op.batch_alter_table('report_impacts', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'impacts', ['impact_id'], ['id'])

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('accused_relation',
               existing_type=mysql.ENUM('jefe_directo', 'companero', 'persona_a_cargo', 'proveedor', 'cliente', 'otro', collation='utf8mb4_unicode_ci'),
               nullable=True)
        batch_op.alter_column('frequency',
               existing_type=mysql.ENUM('una_vez', 'mas_de_una_vez', 'reiterada', collation='utf8mb4_unicode_ci'),
               nullable=True)
        batch_op.alter_column('current_risk',
               existing_type=mysql.ENUM('si', 'no', 'no_segura', collation='utf8mb4_unicode_ci'),
               nullable=True)
        batch_op.alter_column('psychological_support',
               existing_type=mysql.ENUM('prioritario', 'orientacion', 'no', 'mas_informacion', collation='utf8mb4_unicode_ci'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.alter_column('psychological_support',
               existing_type=mysql.ENUM('prioritario', 'orientacion', 'no', 'mas_informacion', collation='utf8mb4_unicode_ci'),
               nullable=False)
        batch_op.alter_column('current_risk',
               existing_type=mysql.ENUM('si', 'no', 'no_segura', collation='utf8mb4_unicode_ci'),
               nullable=False)
        batch_op.alter_column('frequency',
               existing_type=mysql.ENUM('una_vez', 'mas_de_una_vez', 'reiterada', collation='utf8mb4_unicode_ci'),
               nullable=False)
        batch_op.alter_column('accused_relation',
               existing_type=mysql.ENUM('jefe_directo', 'companero', 'persona_a_cargo', 'proveedor', 'cliente', 'otro', collation='utf8mb4_unicode_ci'),
               nullable=False)

    with op.batch_alter_table('report_impacts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('report_behaviors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
