"""Report and user model update

Revision ID: 60f64592de38
Revises: 61d40b958e9a
Create Date: 2026-04-06 11:12:29.816727

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '60f64592de38'
down_revision = '61d40b958e9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mime_type', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('uploaded_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reporter_user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('accused_user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('reporter_name', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('closed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('accused_relation_other', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('status', sa.Enum('nuevo', 'en_proceso', 'finalizado'), nullable=False))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('accused_relation',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.Enum('jefe_directo', 'companero', 'persona_a_cargo', 'proveedor', 'cliente', 'otro'),
               existing_nullable=False)
        batch_op.alter_column('frequency',
               existing_type=mysql.ENUM('una_vez', 'repetida', 'reiterada', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('una_vez', 'mas_de_una_vez', 'reiterada'),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('reports_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['accused_user_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['reporter_user_id'], ['id'])
        batch_op.drop_column('reporter_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('document', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('area', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('position', sa.String(length=150), nullable=True))
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=120),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=mysql.ENUM('reportante', 'admin', collation='utf8mb4_unicode_ci'),
               type_=sa.Enum('reporter', 'admin'),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('document_number'))
        batch_op.create_unique_constraint(None, ['document'])
        batch_op.drop_column('full_name')
        batch_op.drop_column('is_active')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('document_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False))
        batch_op.add_column(sa.Column('password_hash', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False))
        batch_op.add_column(sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('full_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('document_number'), ['document_number'], unique=True)
        batch_op.alter_column('role',
               existing_type=sa.Enum('reporter', 'admin'),
               type_=mysql.ENUM('reportante', 'admin', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=120),
               nullable=False)
        batch_op.drop_column('position')
        batch_op.drop_column('area')
        batch_op.drop_column('document')
        batch_op.drop_column('name')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reporter_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('reports_ibfk_1'), 'users', ['reporter_id'], ['id'])
        batch_op.alter_column('frequency',
               existing_type=sa.Enum('una_vez', 'mas_de_una_vez', 'reiterada'),
               type_=mysql.ENUM('una_vez', 'repetida', 'reiterada', collation='utf8mb4_unicode_ci'),
               existing_nullable=False)
        batch_op.alter_column('accused_relation',
               existing_type=sa.Enum('jefe_directo', 'companero', 'persona_a_cargo', 'proveedor', 'cliente', 'otro'),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.drop_column('status')
        batch_op.drop_column('accused_relation_other')
        batch_op.drop_column('closed_at')
        batch_op.drop_column('reporter_name')
        batch_op.drop_column('accused_user_id')
        batch_op.drop_column('reporter_user_id')

    with op.batch_alter_table('evidences', schema=None) as batch_op:
        batch_op.drop_column('uploaded_at')
        batch_op.drop_column('mime_type')

    # ### end Alembic commands ###
