"""initial schema 2

Revision ID: 61d40b958e9a
Revises: 
Create Date: 2026-04-01 08:19:03.930167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61d40b958e9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('behaviors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('impacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('document_number', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('role', sa.Enum('reportante', 'admin'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_number'),
    sa.UniqueConstraint('email')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('reporter_area', sa.String(length=150), nullable=False),
    sa.Column('reporter_position', sa.String(length=150), nullable=False),
    sa.Column('accused_name', sa.String(length=150), nullable=False),
    sa.Column('accused_position', sa.String(length=150), nullable=False),
    sa.Column('accused_area', sa.String(length=150), nullable=False),
    sa.Column('accused_relation', sa.String(length=50), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=False),
    sa.Column('frequency', sa.Enum('una_vez', 'repetida', 'reiterada'), nullable=False),
    sa.Column('has_evidence', sa.Enum('si', 'no', 'investigar_sin_pruebas'), nullable=False),
    sa.Column('current_risk', sa.Enum('si', 'no', 'no_segura'), nullable=False),
    sa.Column('psychological_support', sa.Enum('prioritario', 'orientacion', 'no', 'mas_informacion'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_behaviors',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('behavior_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['behavior_id'], ['behaviors.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('report_id', 'behavior_id')
    )
    op.create_table('report_impacts',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('impact_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['impact_id'], ['impacts.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('report_id', 'impact_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_impacts')
    op.drop_table('report_behaviors')
    op.drop_table('evidences')
    op.drop_table('reports')
    op.drop_table('users')
    op.drop_table('impacts')
    op.drop_table('behaviors')
    # ### end Alembic commands ###
